# Generated by Django 5.1.2 on 2024-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_restore'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('suggestions', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='restore',
            old_name='disc',
            new_name='Disc',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='disc',
            new_name='Disc',
        ),
        migrations.AddField(
            model_name='restore',
            name='Created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Created',
            field=models.DateField(auto_now=True),
        ),
    ]
